name: weddingitinerary
description: A Wedding Itinerary application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  intl: #^0.17.0 #for date time to string formatting
  flutter_bloc: #^7.1.0 #for blocks designing
  http: #^0.12.1 #for http communication
  flutter_appauth: ^1.1.0+2 #for auth0 Oauth authentication
  shared_preferences: #for storing local data
  equatable:
  custom_navigation_bar: ^0.8.2
  hexcolor: ^2.0.5
  mongo_dart:
  objectid: 2.0.0
  bloc_concurrency:
  marquee:
  salomon_bottom_bar: ^3.1.0
  gcloud:
  googleapis_auth:
  image_picker:
  mime:
  path_provider:
  image:
  back_button_interceptor:
  carousel_slider:
  maps_launcher:
  url_launcher:
  flutter_keyboard_visibility: ^5.1.0
  flutter_launcher_icons:
  internet_connection_checker: ^0.0.1+3
  permission_handler: ^6.1.1
  flutter_image_compress: ^1.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/iconimage/app_icon.jpeg"

flutter:
  uses-material-design: true
  assets:
    - lib/core/constants/credentials.json
    - lib/core/assets/images/background_image_2.jpeg
    - lib/core/assets/images/background_image_4.jpeg
    - lib/core/assets/images/background_image_7.jpeg
    - lib/core/assets/images/background_image_8.jpeg
    #- lib/core/assets/iconimage/app_icon.jpeg
    - lib/core/assets/images/Durgesh_Weds_Ritika.png